STEPS = step0_repl.re step1_read_print.re step2_eval.re step3_env.re \
	step4_if_fn_do.re step5_tco.re step6_file.re step7_quote.re \
	step8_macros.re step9_try.re stepA_mal.re


all: $(STEPS)

$(STEPS):
	esy build